### ISSUE TITLE
Create Makefile for container build and deploy process

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#1]
Create a Makefile for the building, testing and deploying of singularity containers from definition files in this repository.

Containers defined in ./definitions will be build and tested in ./images and deployed to a specified **deploy target**  , default is ./containers.

Structure:
./definitions/*.def
./images/
./sandboxes
./config

The test target invokes the test (test.sh) script inside the container.

**Comment by brettin** [comment]
Are you good closing this issue? @wilke

**Comment by brettin** [comment]
This looks good now. Closing the issue.
