### ISSUE TITLE
Missing documentation for required scripts inside container

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#2]
I am looking for some documentation explaining which scripts have to be created and made executable inside the container, so that the improve script for example can execute a model, in particular test.sh and train.sh.

**Comment by brettin** [comment]
We need to make test.sh part of the deployment requirements for a near future minor release

**Comment by wilke** [comment]
taking issue

**Comment by wilke** [comment]
I am closing this issue. Testing will resume from scratch for the next release.
