### ISSUE TITLE
Test and mark models for release

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#34]
Build and test all models within the definitions folder.

1. Run make
2. On every model in the build folder, execute the test script test_model.sh :

   `singularity exec --bind ${TEST_DIR}:/candle_data_dir build/${MODEL}.sif train.sh 4 /candle_data_dir`

   or  `test/wrapper_test_images.sh` running all models in the build dir. 

3. Setup automated testing and testing scripts

Models, depends on:

1. #37			
2. #35 
3. #38
4. #41 
5. #36
6. #39 
7. #42 
8. #44 
9. #45 
10. #48 
11. #47 
12. #49
13. #52 
14. #55

**Comment by rajeeja** [comment]
Tested on both lambda and Polaris?
Technically, should work on other places where containers are built

**Comment by wilke** [comment]
> Tested on both lambda and Polaris?
> Technically, should work on other places where containers are built

We build and test first on lambda or any other machine than Polaris. For models passing the initial tests we have to modify the definition file to be able to build on lambda.

**Comment by wilke** [comment]
Adding TGSA to the list.

**Comment by wilke** [comment]
Added SWnet

**Comment by wilke** [comment]
Creating improve branch for models passing exuting train.sh inside container. Switching to improve branch in singularity definitions files.

Updating status in project board: https://github.com/orgs/JDACS4C-IMPROVE/projects/6

**Comment by wilke** [comment]
September release done
