### ISSUE TITLE
Test PathDSP

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#42]
Command: `singularity exec --bind ${TEST_DIR}:/candle_data_dir build/PathDSP.sif train.sh 5 /candle_data_dir --epochs 1`
Status: Failed
Depends on:
- #43 
- https://github.com/JDACS4C-IMPROVE/PathDSP/issues/3

Output:
```
FATAL:   "train.sh": executable file not found in $PATH
```

**Comment by Liuy12** [comment]
I just created a PR for PathDSP

**Comment by wilke** [comment]
I am closing this issue. Testing will resume from scratch for the next release.
