### ISSUE TITLE
Test TranPathDSP

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Singularity#49]
Command: `singularity exec --bind ${TEST_DIR}:/candle_data_dir build/TranPathDSP.sif train.sh 5 /candle_data_dir --epochs 1`
Status: Failed

Output:
```
FATAL:   "train.sh": executable file not found in $PATH
```

**Comment by priyanka9991** [comment]
This model is not candle-ized. Missing train.sh, preprocess.sh and infer.sh.

**Comment by wilke** [comment]
I am closing this issue. Testing will resume from scratch for the next release.
